server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: uw-foodie
    password: uw-foodie
  resources:
    static-locations: classpath:/dist

mybatis:
  configuration:
    map-underscore-to-camel-case : true


