server:
port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.64.134:3308/shopcomment?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  resources:
    static-locations: classpath:/templates  #访问静态页面


